### ISSUE TITLE
__wakeup

### ISSUE THREAD

**Issue by imme-emosol** [byjg/SingletonPatternPHP#2]
In https://github.com/chrisnharvey/PHP-Singleton-Trait/blob/master/Singleton.php __wakeup is also used in the pattern.

So, __wakeup should be added, or
text should be added to the readme explaining why __wakeup is not there.

**Comment by byjg** [comment]
The magic function `__sleep` and `__wakeup`  is only for customize serialization and unserialization ([here](http://php.net/manual/it/oop4.magic-functions.php)). I don't think so if it is necessary. 

The example you send to me it seems the class cannot be serialized. 

```php
class Test
{
        public $a = 10;

        public function __wakeup() {}

        public function __sleep() {}

}

$test = new Test();

print_r(serialize($test));
```

throws the error: `serialize(): __sleep should return an array only containing the names of instance-variables to serialize` what is expected by the documentation. 

So, today I can serialize the singleton class. The wakeup/sleep will only necessary if we do not want to permit serialize; I made an example that the serialization works:

```php
<?php
require "vendor/autoload.php";

class Example
{
    // You need to use the trait here
    use \ByJG\DesignPattern\Singleton;

    public $variable;
    // Put your code below
}

$example = Example::getInstance();
$example->variable = 30;

$serializedExample = serialize($example);
$newExample = unserialize($serializedExample);

print_r($newExample->variable);

echo "\n";
```

**Comment by imme-emosol** [comment]
Thanks for the elaborate answer, with investigation and examples.
So, what do you think about de-/unserializing multiple times .., e.g.: `
   $newExample = unserialize($serializedExample);
   $newExample2 = unserialize($serializedExample);
`

**Comment by byjg** [comment]
Done.

**Comment by imme-emosol** [comment]
very nice :)
